Repository NexusMutual/smart-contracts, pull requests merged in 2024-06, with the labels that each got.

#1129 fix: Fix setProducts script metadata file path
  scripts/products/get-setProducts-txdata.js
Labels: chore

#1081 bug: Update missing updates when expiring cover
  contracts/modules/cover/Cover.sol
  test/integration/Cover/expireCover.js
Labels: bug, in-review

#1132 feat: Add tenderly simulation to setProducts script
  scripts/products/get-setProducts-txdata.js
Labels: chore

#1136 fix: separate allowed pools from fixed price
  contracts/interfaces/ICoverProducts.sol
  contracts/interfaces/IStakingProducts.sol
  contracts/mocks/generic/StakingProductsGeneric.sol
  contracts/mocks/modules/Cover/COMockStakingProducts.sol
  contracts/modules/cover/CoverProducts.sol
  contracts/modules/staking/StakingProducts.sol
  test/integration/setup.js
  test/unit/Cover/setup.js
  test/unit/CoverProducts/setProducts.js
  test/utils/accounts.js
Labels: enhancement, cover-products

#1142 feat: Remove whitespace in Cover Assets csv
  scripts/products/get-setProducts-txdata.js
Labels: chore

#1135 feature: change operator and nft descriptor
  contracts/interfaces/ICompleteStakingPoolFactory.sol
  contracts/interfaces/ICover.sol
  contracts/interfaces/ICoverNFT.sol
  contracts/interfaces/IStakingNFT.sol
  contracts/interfaces/IStakingProducts.sol
  contracts/mocks/generic/CoverGeneric.sol
  contracts/mocks/generic/CoverNFTGeneric.sol
  contracts/mocks/generic/StakingNFTGeneric.sol
  contracts/mocks/generic/StakingProductsGeneric.sol
  contracts/mocks/modules/Cover/COMockStakingProducts.sol
  contracts/mocks/modules/CoverProducts/CPMockCover.sol
  contracts/mocks/modules/StakingPool/SKMockCoverProducts.sol
  contracts/modules/cover/Cover.sol
  contracts/modules/cover/CoverProducts.sol
  contracts/modules/staking/StakingProducts.sol
  test/integration/Cover/changeCoverNFTDescriptor.js
  test/integration/Cover/changeStakingNFTDescriptor.js
  test/integration/StakingProducts/changeStakingPoolFactoryOperator.js
Labels: feature, cover-products
