Repository NexusMutual/smart-contracts, pull requests merged in 2024-07, with the labels that each got.

#1156 feat: Product listing scripts improvements
  scripts/products/get-setProductTypes-txdata.js
  scripts/products/get-setProducts-txdata.js
Labels: enhancement

#1171 Feature: Move ipfs hashes to storage
  contracts/interfaces/ICover.sol
  contracts/interfaces/ICoverProducts.sol
  contracts/mocks/generic/CoverProductsGeneric.sol
  contracts/modules/cover/Cover.sol
  contracts/modules/cover/CoverProducts.sol
  scripts/migrate-cover-products-metadata.js
  test/integration/Cover/buyCover.js
  test/integration/StakingProducts/setProducts.js
  test/unit/Cover/buyCover.js
  test/unit/CoverProducts/setProductTypes.js
  test/unit/CoverProducts/setProductTypesMetadata.js
  test/unit/CoverProducts/setProducts.js
  test/unit/CoverProducts/setProductsMetadata.js
  test/unit/StakingPool/requestAllocation.js
Labels: feature, cover-products

#1185 Add decimals function to Aggregator interface
  contracts/interfaces/IPriceFeedOracle.sol
Labels: enhancement

#1164 feat: Add NexusViewer and AssessmentViewer
  contracts/interfaces/IAssessmentViewer.sol
  contracts/interfaces/INexusViewer.sol
  contracts/interfaces/IStakingViewer.sol
  contracts/mocks/modules/AssessmentViewer/AVMockAssessment.sol
  contracts/mocks/modules/NexusViewer/NVMockAssessmentViewer.sol
  contracts/mocks/modules/NexusViewer/NVMockStakingViewer.sol
  contracts/modules/assessment/AssessmentViewer.sol
  contracts/modules/assessment/AssessmentViews.sol
  contracts/modules/staking/StakingViewer.sol
  contracts/modules/viewer/NexusViewer.sol
  test/fork/utils.js
  test/integration/Cover/buyCover.js
  test/integration/MCR/updateMCR.js
  test/integration/NexusViewer/getClaimableNxm.js
  test/integration/NexusViewer/getStakedNxm.js
  test/integration/NexusViewer/setup.js
  test/integration/setup.js
  test/integration/utils/cover.js
  test/unit/AssessmentViewer/getRewards.js
  test/unit/AssessmentViewer/isStakeLocked.js
  test/unit/AssessmentViewer/setup.js
  test/unit/NexusViewer/getStakedNXM.js
  test/unit/NexusViewer/setup.js
  test/unit/StakingViewer/getManagedStakingPools.js
  test/unit/StakingViewer/getManagerPoolsAndRewards.js
  test/unit/StakingViewer/getManagerTokenRewards.js
  test/unit/StakingViewer/processExpirationsFor.js
  test/unit/StakingViewer/setup.js
  test/utils/index.js
  test/utils/stakingPool.js
Labels: feature, nxm-balance-views

#1195 chore: Update deployments for cover products and viewer contracts
  .solcover.js
  deployments/README.md
  deployments/build.js
  deployments/package-lock.json
  deployments/package.json
  deployments/src/addresses.json
  package-lock.json
  package.json
Labels: chore
